/* #define MASTER_RIGHT */

#define MOUSEKEY_DELAY             80
#define MOUSEKEY_INTERVAL          40
#define MOUSEKEY_MAX_SPEED         40
#define MOUSEKEY_TIME_TO_MAX       40
#define MOUSEKEY_WHEEL_MAX_SPEED   10
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
