#define MOUSEKEY_DELAY             100
#define MOUSEKEY_INTERVAL          25
#define MOUSEKEY_MAX_SPEED         20
#define MOUSEKEY_TIME_TO_MAX       20
#define MOUSEKEY_WHEEL_MAX_SPEED   8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40

MOUSEKEY_ENABLE   = yes
